In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp',
    'Parch','Survived']]

In [10]:
df.head(3)

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1

In [11]:
df.dropna(inplace = True)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [27]:
x = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [28]:
x.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [29]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [30]:
np.mean(cross_val_score(LogisticRegression(), x,y, scoring = 'accuracy', cv = 20))

np.float64(0.6933333333333332)

## Apply Feature Construction

In [31]:
x['Family_size'] = x['SibSp'] + x['Parch'] + 1

In [32]:
x.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [33]:
def Value_family(num):
    if num == 1:
        # alone
        return 0
    elif num >= 1 and num <=4: 
        # small family
        return 1
    else: 
        # large family
        return 2

In [34]:
Value_family(4)

1

In [35]:
x['Family_type'] = x['Family_size'].apply(Value_family)

In [36]:
x.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [38]:
x.drop(columns = ['SibSp','Parch', 'Family_size'], inplace = True)

In [39]:
x.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [40]:
np.mean(cross_val_score(LogisticRegression(), x,y, scoring = 'accuracy', cv = 20))

np.float64(0.7003174603174602)

In [41]:
# i increased accuracy

## Feature splitting

In [42]:
df= pd.read_csv('train.csv')

In [43]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [46]:
df['Title'] = df['Name'].str.split(', ', expand = True)[1].str.split('.', expand = True)[0]

In [47]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [48]:
df['Title'].describe()

count     891
unique     17
top        Mr
freq      517
Name: Title, dtype: object

In [53]:

# Convert 'Survived' to numeric, coercing errors to NaN
df['Survived'] = pd.to_numeric(df['Survived'], errors='coerce')

# Make sure 'Survived' is explicitly converted to float type
df['Survived'] = df['Survived'].astype(float)

# Now group by 'Title' and calculate mean of 'Survived', then sort
(df.groupby('Title')['Survived'].mean()).sort_values(ascending=False)

Title
the Countess    1.000000
Mlle            1.000000
Sir             1.000000
Ms              1.000000
Lady            1.000000
Mme             1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Col             0.500000
Major           0.500000
Dr              0.428571
Mr              0.156673
Jonkheer        0.000000
Rev             0.000000
Don             0.000000
Capt            0.000000
Name: Survived, dtype: float64